task:
  name: Build sbtn for macOS ARM64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  coursier_cache:
    folder: $HOME/Library/Caches/Coursier/v1
  sbt_cache:
    folder: $HOME/.sbt
  build_script: arch -arm64 ./.cirrus/publish-macos-silicon.sh
  binary_artifacts:
    path: "sbt/client/target/bin/sbtn"
